# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170328_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '标题', 'verbose_name_plural': '标题'},
        ),
    ]
