# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_id', to='blog.Blog'),
        ),
    ]
