# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
